# Generated by Django 4.2.11 on 2024-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiDriversCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_driver_id', models.CharField(max_length=250, verbose_name='ID таксиста')),
                ('taxi_driver_status', models.CharField(max_length=250, verbose_name='Статус таксиста')),
                ('taxi_driver_coordinates', models.TextField(verbose_name='Координати таксиста')),
            ],
            options={
                'verbose_name': 'Координати таксиста',
                'verbose_name_plural': 'Координати таксистів',
            },
        ),
    ]
