# Generated by Django 4.2.11 on 2024-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_driver', models.CharField(max_length=150, verbose_name='Таксист')),
                ('opening_time', models.DateTimeField(verbose_name='Час відкриття замовлення')),
                ('closing_time', models.DateTimeField(verbose_name='Час закриття замовлення')),
                ('starting_address', models.TextField(verbose_name='Початкова адреса')),
                ('final_address', models.TextField(verbose_name='Кінцева адреса')),
                ('price', models.FloatField(verbose_name='Ціна')),
            ],
            options={
                'verbose_name': 'Завершене замовлення',
                'verbose_name_plural': 'Завершені замовлення',
            },
        ),
    ]
